#!/bin/bash
# ============================================================================
#
# This is a component of the Aliaswallet shell rpc ui
#
# SPDX-FileCopyrightText: © 2020 Alias Developers
# SPDX-FileCopyrightText: © 2016 SpectreCoin Developers
# SPDX-License-Identifier: MIT
#
# Definition of used constants
#
# Author: 2018 HLXEasy
#
# ============================================================================

# Dialog exit status codes
DIALOG_OK=0
DIALOG_CANCEL=1
DIALOG_HELP=2
DIALOG_EXTRA=3
DIALOG_ITEM_HELP=4
DIALOG_ESC=255
DIALOG_ERROR=-1

# Fields on transaction array (RPC listtransactions)
TA_ACCOUNT=0
TA_ADDRESS=1
TA_AMOUNT=2
TA_BLOCKHASH=3
TA_BLOCKINDEX=4
TA_BLOCKTIME=5
TA_CATEGORY=6
TA_CONFIRMATIONS=7
TA_CURRENCY=8
TA_FEE=9
TA_GENERATED=10
TA_NARRATION=11
TA_TIME=12
TA_TIMERECEIVED=13
TA_TXID=14
TA_VERSION=15

# Fields on wallet info (RPC getinfo)
WALLET_VERSION=0
WALLET_BALANCE=1
WALLET_BALANCE_PRIVATE=2
WALLET_BALANCE_UNCONF=3
WALLET_BALANCE_UNCONF_PRIVATE=4
WALLET_STAKE=5
WALLET_STAKE_PRIVATE=6
WALLET_STAKE_WEIGHT=7
WALLET_STAKE_WEIGHT_PRIVATE=8
WALLET_CONNECTIONS=9
WALLET_DATARECEIVED=10
WALLET_DATASENT=11
WALLET_IP=12
WALLET_UNLOCKED_UNTIL=13
WALLET_ERRORS=14
WALLET_MODE=15
WALLET_STATE=16
WALLET_PROTOCOLVERSION=17
WALLET_WALLETVERSION=18
WALLET_NEWMINT=19
WALLET_RESERVE=20
WALLET_BLOCKS=21
WALLET_TIMEOFFSET=22
WALLET_MONEY_SUPPLY=23
WALLET_PRIVATE_SUPPLY=24
WALLET_PROXY=25
WALLET_PROOF_OF_WORK=26
WALLET_PROOF_OF_STAKE=27
WALLET_TESTNET=28
WALLET_KEYPOOLSIZE=29
WALLET_PAYTXFEE=30
WALLET_MININPUT=31

# Conversion direction
CONVERT_NOTHING=0
CONVERT_PUBLIC_TO_PRIVATE=1
CONVERT_PRIVATE_TO_PUBLIC=2

# Coin type to send
SEND_NOTHING=0
SEND_PUBLIC_COINS=1
SEND_PRIVATE_COINS=2
