#!/bin/bash
# ============================================================================
#
# This is a component of the Aliaswallet shell rpc ui
#
# SPDX-FileCopyrightText: © 2020 Alias Developers
# SPDX-FileCopyrightText: © 2016 SpectreCoin Developers
# SPDX-License-Identifier: MIT
#
# Author: 2018 HLXEasy
#
# ============================================================================

# ============================================================================
# Set global variables for text output(i.e. for main menu).
#
# Interpret embedded "\Z" sequences in the dialog text by the following character,
# which tells dialog to set colors or video attributes: 0 through 7 are the ANSI
# used in curses: black, red, green, yellow, blue, magenta, cyan and white respectively.
# Bold is set by 'b', reset by 'B'.
# Reverse is set by 'r', reset by 'R'.
# Underline is set by 'u', reset by 'U'.
# The settings are cumulative,
# e.g., "\Zb\Z1" makes the following text bold (perhaps bright) red.
# Restore normal settings with "\Zn".
TITLE_BACK=" Alias portemonnee Bash Interface "
TITLE_TRANS=" Recente transacties "
TITLE_INFO=""
TITLE_GAUGE=" Even geduld alstublieft "
TITLE_ERROR=" FOUT "
TITLE_SUCCESS=" Succes "
TITLE_STARTING_DAEMON=" Daemon starten - U moet wachten tot "
TITLE_GOODBYE=" Tot ziens "
TITLE_SEND_PUBLIC=" Openbaar verzenden "
TITLE_SEND_PRIVATE=" Privé verzenden "
TITLE_CONVERT=" munten omzetten "
TITLE_USERCOMMAND=" Voer het commando in "
TITLE_CURL_RESULT=" cURL resultaat "
TITLE_RECEIVE=" Adressen portemonnee "
TITLE_SUGGESTION=" Suggestie "
TITLE_PLACEHOLDER_FUNCTION=" Sorry daarvoor "
TITLE_ENCRYPT_WALLET=" Portemonnee versleutelen "
TITLE_VIEW_TRANSACTIONS=" Pagina "
TITLE_ADV_MENU=" Geavanceerde opties "
TITLE_WALLET_INFO=" Portemonnee informatie "
TITLE_STAKING_INFO=" Staking informatie "
TITLE_PLEASE_CHOOSE=" Gelieve te kiezen "
TITLE_UPDATE_BINARIES=" Bijwerken van Alias portemonnee "
TITLE_LANGUAGE_SELECTION=" Huidige taal: Nederlands "
TITLE_AVAILABLE_VERSIONS=" Beschikbare versies "
TITLE_SYSTEM_STATS=" Systeemstatistieken "
#
BUTTON_LABEL_ENCRYPT="Versleutelen"
BUTTON_LABEL_RESTART_DAEMON="Daemon herstarten"
BUTTON_LABEL_ENTER="Enter"
BUTTON_LABEL_OK="Oké"
BUTTON_LABEL_LEAVE="Vertrekken"
BUTTON_LABEL_CONTINUE="Continu"
BUTTON_LABEL_PREVIOUS="Vorige"
BUTTON_LABEL_NEXT="Volgende"
BUTTON_LABEL_SEND="Verzenden"
BUTTON_LABEL_EXECUTE="Uitvoeren"
BUTTON_LABEL_HELP="Help"
BUTTON_LABEL_ADDRESS_BOOK="Adressenboek"
BUTTON_LABEL_MAIN_MENU="Hoofdmenu"
BUTTON_LABEL_SHOW_STAKES="Stakes tonen"
BUTTON_LABEL_HIDE_STAKES="Stakes verbergen"
BUTTON_LABEL_JUST_LEAVE="Nee, verlaat gewoon de gebruikersinterface"
BUTTON_LABEL_STOP_DAEMON="Yes, stop daemon"
BUTTON_LABEL_I_HAVE_UNDERSTOOD="Ja, ik begrijp het"
BUTTON_LABEL_SHOW_BALANCE="Saldo tonen"
BUTTON_LABEL_HIDE_BALANCE="Saldo verbergen"
BUTTON_LABEL_PUBLIC_TO_PRIVATE="Openbaar naar privé"
BUTTON_LABEL_PRIVATE_TO_PUBLIC="Privé naar openbaar"
BUTTON_LABEL_CLOSE="Venster sluiten"
BUTTON_LABEL_RETURN="Terugkeren"
BUTTON_LABEL_EXIT="Exit"
BUTTON_LABEL_UPDATE_TO_LATEST_RELEASE="laatste uitgave"
BUTTON_LABEL_UPDATE_CHOOSE_VERSION="Versie kiezen"
BUTTON_LABEL_REFRESH="Vernieuwen"
BUTTON_LABEL_BACK="Terug"
BUTTON_LABEL_YES="Ja"
BUTTON_LABEL_NO="Nee"
#
# Main Menu
CMD_MAIN_LOCK_WALLET="Vergrendelden"
EXPL_CMD_MAIN_WALLETLOCK="Portemonnee is vergrendeld, geen staking meer."
CMD_MAIN_UNLOCK_WALLET="Ontgrendelen"
EXPL_CMD_MAIN_WALLETUNLOCK="Portemonnee alleen voor staking geopend."
CMD_MAIN_ENCRYPT_WALLET="Encrypt"
EXPL_CMD_MAIN_WALLETENCRYPT="Portemonnee versleutelen."
CMD_MAIN_REFRESH="Bijwerken"
EXPL_CMD_MAIN_REFRESH="Vernieuw de interface."
CMD_MAIN_TRANS="Transacties"
EXPL_CMD_MAIN_VIEWTRANS="Alle transacties bekijken."
CMD_MAIN_SEND="Munten verzenden"
EXPL_CMD_MAIN_SEND="Eén van beide: Openbaar of Privé."
CMD_MAIN_CONVERT_COINS="Munten omzetten"
EXPL_CMD_MAIN_CONVERT_COINS="Openbaar <-> Privé."
CMD_MAIN_RECEIVE="Ontvangen"
EXPL_CMD_MAIN_RECEIVE="Portemonnee adressen tonen."
CMD_MAIN_ADVANCED_MENU="Geavanceerd"
EXPL_CMD_MAIN_ADVANCEDMENU="Geavanceerde opties."
CMD_MAIN_QUIT="Afsluiten"
EXPL_CMD_MAIN_EXIT="Verlaat deze interface."
#
# Advanced Menu
CMD_GET_SYSTEM_STATS="Systeem"
EXPL_CMD_GET_SYSTEM_STATS_INFO="Systeem informatie weergeven."
CMD_USER_COMMAND="Commando"
EXPL_CMD_USER_COMMAND="Commando naar daemon sturen."
CMD_DEVELOPER_COMMAND="Commando voor ontwikkelaar"
EXPL_CMD_DEVELOPER_COMMAND="Ontwikkelaarsmodus."
CMD_CHANGE_WALLET_PW="Opnieuw versleutelen"
EXPL_CMD_CHANGE_WALLET_PW="Wijzig het wachtwoord van de portemonnee."
CMD_STAKING_ANALYSE="Staking"
EXPL_CMD_STAKING_ANALYSE="Krijg staking details."
CMD_GET_WALLET_INFO="Portemonnee"
EXPL_CMD_GET_WALLET_INFO="Portemonnee informatie tonen."
CMD_UPDATE="Update"
EXPL_CMD_UPDATE="Alias portemonnee binaries bijwerken"
CMD_VIEW_LOG="Logfile"
EXPL_CMD_VIEW_LOG="Bekijk log"
CMD_CHANGE_LANGUAGE="Taal"
EXPL_CMD_CHANGE_LANGUAGE="Wijzig de taal van deze gebruikersinterface."
CMD_GET_PEER_INFO="Verbindingen"
EXPL_CMD_GET_PEER_INFO="Geef de huidige verbindingen weer."
CMD_MAIN_MENU="Hoofdmenu"
EXPL_CMD_MAIN_MENU="Ga terug naar het hoofdmenu."
#
# Error Feedback
ERROR_MAINMENU_FATAL="Onverwachte ernstige fout in het dialoogvenster van het hoofdmenu."
ERROR_ADVMENU_FATAL="Onverwachte ernstige fout in het dialoogvenster van het geavanceerd menu."
ERROR_SYSTEM_STATS_FATAL="Onverwachte ernstige fout in het dialoogvenster van systeemstatistieken."
ERROR_USERCOMMAND_FATAL="Onverwachte ernstige fout in het dialoogvenster van gebruikersopdrachten."
ERROR_PW_FATAL="Onverwachte ernstige fout in het wachtwoordvenster."
ERROR_SEND_FATAL="Onverwachte ernstige fout in het verzend dialoogvenster."
ERROR_CONVERT_FATAL="Onverwachte ernstige fout in het dialoogvenster van munt omzetten."
ERROR_TRANS_FATAL="Onverwachte ernstige fout in het dialoogvenster van alle transacties."
ERROR_GOODBYE_FATAL="Onverwachte ernstige fout in het daemon stop (tot ziens) dialoogvenster."
ERROR_SEND_INVALID_ADDRESS="\Z1U heeft een ongeldig adres ingevoerd.\Zn\n\nEen geldig openbaar adres moet in de vorm:\n- Begint met \"S\"\n- Lengte 27-34\n- Hoofdletter \"O\", \"I\", kleine letter \"l\", en de nummer \"0\" worden nooit gebruikt om verwarring te voorkomen."
ERROR_SEND_INVALID_PRIVATE_ADDRESS="\Z1U heeft een ongeldig adres ingevoerd.\Zn\n\nEen geldig privé adres moet in de vorm:\n- Lengte 102 karakters\n- Hoofdletter \"O\", \"I\", kleine letter \"l\", en de nummer \"0\" worden nooit gebruikt om verwarring te voorkomen."
ERROR_SEND_INVALID_AMOUNT="Bedrag moet een nummer zijn, met:\n- groter dan 0\n- max. 8 cijfers achter de punt"
ERROR_CURL_MSG_PROMPT="CURL foutmelding:"
ERROR_401_UNAUTHORIZED="Fout: RPC aanmelding mislukt. Heeft u het wachtwoord gewijzigd zonder de daemon opnieuw op te starten? Opmerking: je kunt de daemon stoppen met het commando: wallet-stop"
ERROR_DAEMON_NO_CONNECT_FROM_REMOTE="Er kon geen verbinding worden gemaakt met de Alias portemonnee daemon.\nMogelijk moet u uw configuratie controleren."
ERROR_DAEMON_NO_CONNECT="Daemon reageerde niet binnen 60 sec.\nEr kon geen verbinding tot stand worden gebracht met de Alias-portemonnee daemon.\nU moet uw configuratie controleren."
#
# use \ for a new line - note: there will be no auto line breaking
ERROR_DAEMON_ALREADY_RUNNING="Alias portemonnee (daemon) is al actief, maar er kon geen verbinding tot stand worden gebracht. Even geduld alstublieft."
ERROR_DAEMON_STARTING="Alias portemonnee werkt nog niet, zal nu starten...."
ERROR_DAEMON_WAITING_BEGIN="Daemon heeft wat tijd nodig om te initialiseren. Wacht 1 minuut op de daemon..."
ERROR_DAEMON_WAITING_MSG="seconden te gaan..."
ERROR_DAEMON_WAITING_MSG_SUCCESS="Daemon is verbonden. Alles is in orde."
ERROR_DAEMON_WAITING_END="Helemaal klaar. Interface starten..."
#
TEXT_HEADLINE_WALLET_INFO="Portemonnee informatie"
TEXT_BALANCE="Saldo"
TEXT_CURRENCY="Openbaar"
TEXT_CURRENCY_PRIVATE="Privé"
TEXT_WALLET_STATE="Portemonnee"
TEXT_WALLET_HAS_NO_PW="\Z1Geen wachtwoord\Zn"
TEXT_WALLET_IS_UNLOCKED="\Z4Ontgrendeld\Zn"
TEXT_WALLET_IS_LOCKED="\Z1Vergrendeld\Zn"
#
TEXT_HEADLINE_CLIENT_INFO="Client informatie"
TEXT_DAEMON_VERSION="Versie"
TEXT_DAEMON_ERRORS_DURING_RUNTIME="Errors"
TEXT_DAEMON_NO_ERRORS_DURING_RUNTIME="geen"
TEXT_DAEMON_IP="IP"
TEXT_DAEMON_PEERS="Verbindingen"
TEXT_DAEMON_DOWNLOADED_DATA="Download"
TEXT_DAEMON_UPLOADED_DATA="Upload"
#
TEXT_HEADLINE_STAKING_INFO="Staking Informatie"
TEXT_STAKING_STATE="Staking"
TEXT_STAKING_ON="\Z4AAN\Zn"
TEXT_STAKING_OFF="\Z1UIT\Zn"
TEXT_STAKING_COINS="Munten"
TEXT_MATURING_COINS="Rijpen"
TEXT_EXP_TIME="Verwachte tijd"
TEXT_STAKING_AVAILABLE="Beschikbaar"
TEXT_STAKING_STAKED="Staked"
#
TEXT_STAKE="\Z4STAKE\Zn"
TEXT_IMMATURE="\Z5ONRIJP\Zn"
TEXT_RECEIVED="\Z2ONTVANGEN\Zn"
TEXT_TRANSFERRED="\Z1VERZONDEN\Zn"
TEXT_CONTRIBUTE="\Z6CONTRIBUTIE\Zn"
TEXT_CONFIRMATIONS="Bevestigingen"
TEXT_ADDRESS="Adres"
TEXT_TXID="TxID"
TEXT_NARRATION="Commentaar"
TEXT_FEE="Vergoeding"
#
TEXT_CLIPBOARD_HINT="On Linux: Gebruik \Z6[CTRL]\Zn + \Z6[SHIFT]\Zn + \Z6[V]\Zn om vanaf het klembord te plakken."
TEXT_SEND_DESTINATION_ADDRESS_EXPL="Bestemmingsadres"
TEXT_SEND_DESTINATION_ADDRESS="Adres"
TEXT_SEND_AMOUNT_EXPL="Bedrag van"
TEXT_SEND_AMOUNT="Bedrag"
TEXT_SEND_EXPL="Voer het bestemmingsadres in."
TEXT_SEND_NARRATION="Commentaar"
#
TEXT_PW_EXPL="Voer het wachtwoord voor de portemonnee in"
TEXT_CURRENT_PW_EXPL="Voer het huidige portemonnee wachtwoord in"
TEXT_NEW_PW1_EXPL="Voer een nieuw portemonnee wachtwoord in"
TEXT_NEW_PW2_EXPL="Voer het nieuwe wachtwoord opnieuw in"
TEXT_NO_PASS_GIVEN="Geen wachtwoord ingevoerd"
TEXT_NO_NEW_PASS_GIVEN="Geen nieuw wachtwoord ingevoerd"
TEXT_NEW_PASS_NOT_EQUAL="Nieuwe wachtwoorden komen niet overeen"
TEXT_PASS_CHANGE_SUCCESSFUL="Wachtwoord wijziging succesvol veranderd"
TEXT_WALLET_ENCRYPTION_SUCCESSFUL="Portemonnee is succesvol versleuteld. Daemon herstarten..."
#
TEXT_USERCOMMAND_EXPL="Hier kun je commando's invoeren die naar de Daemon worden gestuurd."
TEXT_USERCOMMAND_CMD_EXPL="Help intypen voor informatie"
TEXT_USERCOMMAND_CMD="Commando"
TEXT_USERCOMMAND_PARAMS_EXPL="gescheiden door spaties"
TEXT_USERCOMMAND_PARAMS="Parameter"
TEXT_USERCOMMAND_AMOUNT="Bedrag"
#
TEXT_SYSTEM="System"
TEXT_MAX_FREQENCY="Max. Frequentie"
TEXT_THRESHOLD="Drempel"
TEXT_TEMPERATURE="Temperatuur"
TEXT_SD_CARD="SD Kaart"
TEXT_FREE_DISK_SPACE="Beschikbare vrije schijfruimte"
TEXT_FREE_RAM="Beschikbare vrije RAM"
TEXT_OS="Besturingssysteem"
TEXT_KERNEL="Linux Kernel Versie"
TEXT_SWAP_DISABLED="Omwisselen is uitgeschakeld."
TEXT_SWAP_SIZE="Grote veranderen"
#
TEXT_GAUGE_ALLDONE="Helemaal klaar."
TEXT_GAUGE_DEFAULT="Gegevens ophalen van daemon..."
TEXT_GAUGE_GET_INFO="Algemene informatie gegevens ophalen van daemon..."
TEXT_GAUGE_PROCESS_INFO="Algemene informatie gegevens verwerken..."
TEXT_GAUGE_GET_STAKING_DATA="Staking van daemon halen..."
TEXT_GAUGE_PROCESS_STAKING_DATA="Staking gegevens verwerken..."
TEXT_GAUGE_GET_TRANS="Transactie gegevens ophalen van daemon..."
TEXT_GAUGE_PROCESS_TRANS="Verwerken van transactie gegevens..."
#
TEXT_GOODBYE_WARNING="\Z1Als u van plan bent het systeem af te sluiten, dan moet de daemon eerst worden gestopt om inconsistenties in de database te voorkomen!\Zn\n\nWil je de daemon stoppen (geen staking meer) of gewoon de gebruikersinterface verlaten?\Zn"
TEXT_GOODBYE_DAEMON_STILL_RUNNING="Daemon draait nog steeds."
TEXT_GOODBYE_DAEMON_STOPPED="Daemon gestopt."
TEXT_GOODBYE_FEEDBACK="Alle feedback wordt op prijs gesteld, laat het ons alstublieft weten. Dank je!"
TEXT_GOODBYE_DAEMON_NOT_SYNCED="De Alias portemonnee daemon is nog steeds niet volledig gesynchroniseerd.\n\nTerug gaan naar de logboekuitvoer of de gebruikersinterface verlaten?"
#
TEXT_LOGFILE_HEADER="De daemon is gesynchroniseerd als je ziet \Z1'height='\Zn gevolgd door de huidige blockchain hoogte op de log uitvoer hieronder. Even geduld alstublieft, dit zal even duren! Scroll naar links / rechts met de pijltjes toetsen."
#
TEXT_FEEDBACK_WALLET_LOCKED="Portemonnee is succesvol vergrendeld.\n\n\Z5U kunt niet meer staken.\Zn\n\nGebruik \Z4${CMD_MAIN_UNLOCK_WALLET}\Zn in het hoofdmenu om de portemonnee te ontgrendelen alleen voor staking."
TEXT_FEEDBACK_WALLET_UNLOCKED="Portemonnee is succesvol ontgrendeld."
TEXT_SUGGESTION_STAKING="Na het ontgrendelen van de portemonnee duurt het even voordat de daemon de staking status heeft bijgewerkt.\nGebruik de \Z4${CMD_MAIN_REFRESH}\Zn commando in het hoofdmenu om het scherm te vernieuwen."
TEXT_FEEDBACK_RECEIVE="Terug naar het hoofdmenu."
TEXT_DEFAULT_PUBLIC_ADDRESS="Standaard Openbaar adres"
TEXT_DEFAULT_PRIVATE_ADDRESS="Standaard Privé adres"
#
TEXT_SEND_UNLOCK_WALLET_AGAIN="Notice\nHoud er rekening mee dat:\nU de portemonnee moet ontgrendelen om opnieuw te staken.\n"
TEXT_SUGGESTION_TO_INCREASE_TERMINAL_SIZE="\nVergroot de terminalgrootte ten minste tot"
TEXT_PLACEHOLDER_FUNCTION="\nNog in ontwikkeling...\n\nSorry, op dit moment slechts een tijdelijke aanduiding."
#
TEXT_ESTIMATIONS="Schattingen"
TEXT_ONE_MONTH="één maand"
TEXT_HALF_YEAR="half jaar"
TEXT_ONE_YEAR="één jaar"
TEXT_TWO_YEARS="twee jaar"
TEXT_THREE_YEARS="drie jaar"
TEXT_FOUR_YEARS="vier jaar"
TEXT_FIVE_YEARS="vijf jaar"
TEXT_STAKING_ANALYSIS_TIMEFRAME="Geschatte tijdsbestek"
TEXT_STAKING_ANALYSIS_LAST_THOUSAND="Binnen de laatste 1000 transacties"
TEXT_STAKING_ANALYSIS_AMOUNTS="Staking transacties"
TEXT_STAKING_ANALYSIS_TOTAL_REWARD="Totale beloning"
TEXT_STAKING_ANALYSIS_TOTAL_TODAY="Totale aantal munten"
TEXT_STAKING_ANALYSIS_REWARD_PER_YEAR="- Staking belonings percentage per jaar"
TEXT_STAKING_ANALYSIS_COINS_IN_ONE_MONTH="- Aantal munten in één maand"
TEXT_STAKING_ANALYSIS_STAKED_COINS_IN="- Staked aantal munten in"
TEXT_STAKING_ANALYSIS_TOTAL_COINS_IN="- Totale aantal munten in"
#
TEXT_COIN_TYPE_TO_SEND_QUESTION="\nWelk type munt wilt u verzenden?"
TEXT_CONVERSION_QUESTION="\nIn welke richting wil je converteren?"
TEXT_AMOUNT_TO_CONVERT="Bedrag voor het omzetten"
#
TEXT_QUESTION_DO_UPDATE="Update Alias portemonnee binaries?\nAlias portemonnee daemon wordt gestopt!\n"
TEXT_UPDATE_CANCELED="Update geannuleerd"
TEXT_UPDATE_CHOOSE_VERSION_HINT="Selecteer de gewenste versie met spatiebalk:"
#
TEXT_CHOOSE_LANGUAGE="Kies een taal"
TEXT_CHOOSE_LANGUAGE_CANCELED="Taal wisselen geannuleerd"
#
TEXT_USE_AT_YOUR_OWN_RISC="                   Gebruik op eigen risico!\n\n"
#
TEXT_BOOTSTRAPPING="Installatie van de bootstrap blockchain is bezig, even geduld alstublieft..."
TEXT_ALIAS_SERVICE_NOT_ENABLED="De alias portemonnee service is niet geactiveerd en zal daarom niet werken na de volgende herstart. De service nu activeren?"
